### ISSUE TITLE
How to manage roles

### ISSUE THREAD

**Issue by papyr** [akasarto/skeleton-system-netfx-mvc5#8]
Hello, this is a great great template. Very clean!!

1. Can you please add some manage roles, users in role,  RolesView: list of roles with users in role. It would be a great help to learn from.
2. Also, I saw you .tpls in the read me, what happens if I need another model besides your base model, should I just add two models to the View
3. Can you please add a couple more notes around the Area, Controllers and View and how you are managing that.
4. Which objects should we use to interact with user and role, I see more than a few.
5. How can we attach custom claims/properties to the user without overloading the user object too much. I have a long list of properties i need to show for each user, but dont want to weigh down user.
6. Nuget vs Libman, this is very interesting certainly learning a lot.

thanks

**Comment by Santosh822** [comment]
Any Update on Role Management ?? Please, let me Know.
